# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-19 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follows',
            name='user_id',
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='ownerid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bio',
            name='ownerid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comments',
            name='ownerid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversations',
            name='ownerid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='convomembers',
            name='userid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='convomessages',
            name='userid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='follows',
            name='userid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='likes',
            name='ownerid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notifications',
            name='ownerid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='ownerid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='ownerid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='official',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='convomembers',
            name='convo_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='convomessages',
            name='convo_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='follows',
            name='follow_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='likes',
            name='post_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='recipient_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='sender_id',
            field=models.IntegerField(default=0),
        ),
    ]
