# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-19 19:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20161119_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerid', models.IntegerField(default=0)),
                ('bio_desc', models.CharField(default='', max_length=150)),
                ('bio_link', models.CharField(default='', max_length=150)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bio_owner', to='webapp.Accounts')),
            ],
            options={
                'db_table': 'bio',
            },
        ),
        migrations.RemoveField(
            model_name='bio',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='following',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='posts',
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_owner', to='webapp.Accounts'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='comment_owner', to='webapp.Accounts'),
        ),
        migrations.AlterField(
            model_name='conversations',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='convo_owner', to='webapp.Accounts'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='like_owner', to='webapp.Accounts'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notif_owner', to='webapp.Accounts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='post_owner', to='webapp.Accounts'),
        ),
        migrations.DeleteModel(
            name='Bio',
        ),
        migrations.DeleteModel(
            name='Stats',
        ),
    ]
