# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-19 19:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20161119_1948'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='accountbio',
            table='account_bio',
        ),
        migrations.AlterModelTable(
            name='accountinfo',
            table='account_info',
        ),
    ]
