# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-19 20:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20161119_1953'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.IntegerField(default=0)),
                ('userid', models.IntegerField(default=0)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_active', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'convo_members',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerid', models.IntegerField(default=0)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('last_active', models.DateField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_owner', to='webapp.Accounts')),
            ],
            options={
                'db_table': 'groups',
            },
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='group_rel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_member_rel', to='webapp.Groups'),
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='group_user', to='webapp.Accounts'),
        ),
    ]
