# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-19 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20161119_2009'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownerid', models.IntegerField(default=0)),
                ('followers', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='webapp.Accounts')),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to='webapp.Accounts')),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='webapp.Accounts')),
                ('likes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='webapp.Accounts')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats_owner', to='webapp.Accounts')),
                ('posts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='webapp.Accounts')),
            ],
            options={
                'db_table': 'stats',
            },
        ),
    ]
