# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-19 20:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_accountstats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountstats',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='accountstats',
            name='following',
        ),
        migrations.RemoveField(
            model_name='accountstats',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='accountstats',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='accountstats',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='accountstats',
            name='posts',
        ),
        migrations.AlterField(
            model_name='comments',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_owner', to='webapp.Accounts'),
        ),
        migrations.AlterField(
            model_name='conversations',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convo_owner', to='webapp.Accounts'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_owner', to='webapp.Accounts'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_owner', to='webapp.Accounts'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notif_owner', to='webapp.Accounts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_owner', to='webapp.Accounts'),
        ),
        migrations.DeleteModel(
            name='AccountStats',
        ),
    ]
