# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-19 20:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20161119_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountbio',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='accountinfo',
            name='owner',
        ),
    ]
