# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-19 20:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_auto_20161119_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountbio',
            name='owner',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='biography_owner', to='webapp.Accounts'),
        ),
        migrations.AddField(
            model_name='accountinfo',
            name='owner',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='information_owner', to='webapp.Accounts'),
        ),
        migrations.AlterModelTable(
            name='accountbio',
            table=None,
        ),
        migrations.AlterModelTable(
            name='accountinfo',
            table=None,
        ),
    ]
