# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-19 21:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20161119_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmembers',
            name='user',
        ),
        migrations.RemoveField(
            model_name='groups',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='notifications',
            name='ownerid',
        ),
        migrations.AddField(
            model_name='groupmembers',
            name='user_rel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='group_user', to='webapp.Accounts'),
        ),
        migrations.AddField(
            model_name='groups',
            name='owner_rel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='group_owner', to='webapp.Accounts'),
        ),
        migrations.AlterField(
            model_name='accountbio',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='biography_owner', to='webapp.Accounts'),
        ),
        migrations.AlterField(
            model_name='accountinfo',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='information_owner', to='webapp.Accounts'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comment_owner', to='webapp.Accounts'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post_rel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webapp.Posts'),
        ),
        migrations.AlterField(
            model_name='conversations',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='convo_owner', to='webapp.Accounts'),
        ),
        migrations.AlterField(
            model_name='convomembers',
            name='convo_rel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='convo_member_rel', to='webapp.Conversations'),
        ),
        migrations.AlterField(
            model_name='convomembers',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='convo_user', to='webapp.Accounts'),
        ),
        migrations.AlterField(
            model_name='convomessages',
            name='convo_rel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='convo_msg_rel', to='webapp.Conversations'),
        ),
        migrations.AlterField(
            model_name='convomessages',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='convo_user_msg', to='webapp.Accounts'),
        ),
        migrations.AlterField(
            model_name='follows',
            name='follow_rel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='follow_rel', to='webapp.Accounts'),
        ),
        migrations.AlterField(
            model_name='follows',
            name='user_rel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user_rel', to='webapp.Accounts'),
        ),
        migrations.AlterField(
            model_name='groupmembers',
            name='group_rel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='group_member_rel', to='webapp.Groups'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='like_owner', to='webapp.Accounts'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='post_rel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='webapp.Posts'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='recipient_rel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='notif_recipient_owner', to='webapp.Accounts'),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='sender_rel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='notif_sender_owner', to='webapp.Accounts'),
        ),
        migrations.AlterField(
            model_name='posts',
            name='owner',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='post_owner', to='webapp.Accounts'),
        ),
        migrations.AlterModelTable(
            name='groupmembers',
            table='group_members',
        ),
    ]
