# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-19 21:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_auto_20161119_2110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountBio',
        ),
        migrations.DeleteModel(
            name='AccountInfo',
        ),
        migrations.AddField(
            model_name='accounts',
            name='bio_desc',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='accounts',
            name='bio_link',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='accounts',
            name='interests',
            field=models.CharField(default='', max_length=1725),
        ),
        migrations.AddField(
            model_name='accounts',
            name='seeking',
            field=models.CharField(default='', max_length=1725),
        ),
    ]
